services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    hostname: wyze-bridge # For tailscale
    restart: unless-stopped
    ports:
      - 1935:1935 # RTMP rtmp://localhost:1935/mystream?user=myuser&pass=mypass
      - 1936:1936 # RTMP rtmps://localhost:1936/mystream?user=myuser&pass=mypass
      - 2935:2935 # RTMPS rtmps://localhost:2935/mystream?user=myuser&pass=mypass
      - 2936:2936 # RTMPS rtmps://localhost:2936/mystream?user=myuser&pass=mypass
      - 8000:8000/udp # RTSP UDP/RTP rtsp://localhost:8000/mystream
      - 8001:8001/udp # RTSP UDP/RTCP rtsp://localhost:8001/mystream
      - 8002:8002/udp # RTP Multicast
      - 8003:8003/udp # RTP Multicast control
      - 8189:8189/udp # WebRTC ICE/UDP
      - 8322:8322 # TCP/TLS/RTSPS rtsps://localhost:8322/mystream
      - 8554:8554 # RTSP rtsp://localhost:8554/mystream
      - 8888:8888 # HLS http://localhost:8888/mystream
      - 8889:8889 # WebRTC http://localhost:8889/mystream and http://localhost:8889/mystream/whep
      - 8890:8890/udp # SRT UDP srt://localhost:8890?streamid=read:mystream:myuser:mypass
      - 5000:5000 # WEB-UI http://localhost:5000/mystream
    cap_add: [NET_ADMIN]
    environment:
      - TS_AUTHKEY=tskey-client-notAReal-OAuthClientSecret1Atawk
      - TS_EXTRA_ARGS=--accept-routes
      - TS_USERSPACE=false
    volumes:
      - /dev/net/tun:/dev/net/tun
  wyze-bridge:
    container_name: wyze-bridge
    restart: unless-stopped
    image: idisposablegithub365/wyze-bridge:latest
    depends_on: [tailscale]
    network_mode: service:tailscale
    environment:
      # [OPTIONAL] Credentials can be set in the WebUI
      # API Key and ID can be obtained from the wyze dev portal:
      # https://developer-api-console.wyze.com/#/apikey/view
      - WYZE_EMAIL=
      - WYZE_PASSWORD=
      - API_ID=
      - API_KEY=
      # [OPTIONAL] IP Address of the host to enable WebRTC e.g.,:
      # - WB_IP=192.168.1.122
      # WebUI and Stream authentication:
      - WB_AUTH=True # Set to false to disable web and stream auth.
      # WB_USERNAME=
      # WB_PASSWORD=